spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:karma_db
    username: root
    password: sep11Jes
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /console
