server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: NON_NULL
  resources:
    add-mappings: true
  banner:
    location: classpath:banner.txt
  profiles:
    active: local
#    active: heroku