spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/karma_db?autoReconnect=true&useSSL=false
    username: root
    password: sep11Jes
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true