insert into karma (id, number, missing, situation, improve) values (null, 1,  'En vidas pasadas tuvo dificultad para tomar decisiones, no pudo aprender el valor de la independencia, tuvo miedo de ser líder', 'Debe confiar más en su propio juicio y en sus habilidades. Algunos problemas lo obligaran a improvisar soluciones. Habrá una constante solicitud para que usted ayude a otros', 'Debe aprender a estimular su osadía, tomar decisiones, afirmar su individualidad y tener confianza en sus propias opiniones');
insert into karma (id, number, missing, situation, improve) values (null, 2,  'Tuvo dificultad en ser tolerante y diplomático o al contrario fue una persona demasiado paciente y termino por volverse sumiso. No le preocuparon los detalles e ignoró los sentimientos de otros', 'Se le exige paciencia y comprensión para entender las reacciones, sentimientos, gustos, deseos e ideas ajenas', 'Debe aprender a perdonar, trabajar, obedecer, y lidiar con las cosas con las que generalmente no está de acuerdo');
insert into karma (id, number, missing, situation, improve) values (null, 3,  'Se reusó a mostrar sus talentos por timidez inhibición, miedo a la crítica o falta de aplausos. Permitió que otros reprimieran o sofocaran sus ideas y su creatividad', 'Se hace necesario mostrar optimismo y capacidad para exponer las ideas. Usted debe decir lo que piensa, lidiar con el público, dejar su concha protectora y actuar', 'Debe aprender a expresar sus sentimientos, derrochar entusiasmo, poner en práctica sus dones, actuar con mucha seguridad y enfrentar los obstáculos con madurez');
insert into karma (id, number, missing, situation, improve) values (null, 4,  'Usted no supo ser metódico y organizado. Hizo todo apresuradamente, buscando atajos que le permitieran llegar más rápido a la meta deseada', 'Deberá pagar por los trabajos de rutina. Tendrá que acompañar de cerca todas las situaciones. Todo lo que haga le exigirá esfuerzo y dedicación', 'Debe aprender a adoptar un modo de vida ordenado sin olvidad jamás que la calidad es mucho mejor que la cantidad');
insert into karma (id, number, missing, situation, improve) values (null, 5,  'No tuvo libertad o no supo hacer buen uso de ella. fue común el miedo a los cambios repentinos, a lo desconocido y a las cosas o situaciones extrañas de las que pudo haber aprendido', 'Cambio, nuevas personas e ideas, dificultad en reprimir y reprimirse, problemas en las relaciones domésticas, familiares y laborales', 'Debe aprender a ajustarse a los cambios y a relacionarse con los demás diversos tipos de personas y situaciones');
insert into karma (id, number, missing, situation, improve) values (null, 6,  'No se adaptó al ambiente en el que vivía. Estaba tan preocupado consigo mismo que evito cualquier tipo de responsabilidad. Pudo haber sido un gran problema para su familia', 'Frustraciones y la posibilidad de vivir una pasión problemática con una persona mucho más vieja o más joven que usted', 'Debe aprender a comprender las necesidades de otros, reforzar los lazos familiares y comunitarios, asumir responsabilidades domésticas y sociales');
insert into karma (id, number, missing, situation, improve) values (null, 7,  'Aprendió mucho en vidas anteriores pero no compartió su aprendizaje. Perteneció a un grupo místico o científico e hizo mal uso de las lecciones recibidas', 'Sensación de no ser amado, miedo al rechazo, búsqueda espiritual solitaria, necesidad de hacer las cosas bien', 'Debe aprender a desarrollar su mente y su lado intuitivo, a meditar, a aprender con los otros y enseñar a los demás a mirar de cerca las cosas y buscar la verdad');
insert into karma (id, number, missing, situation, improve) values (null, 8,  'En su vida pasada usted hizo mal uso del poder. Por descuido o egoísmo, manejo equivocadamente asuntos financieros', 'Su lado emocional es contantemente probado. Tiene dificultad para delegar y establecer algún control financiero. Teme que lo traicionen', 'Debe aprender a dirigir los negocios, manejar el dinero, controlarse emocionalmente y desarrollar su liderazgo');
insert into karma (id, number, missing, situation, improve) values (null, 9,  'Indica que fue muy racional y que no supo expresar sus emociones. No demostró amor y no permitió que lo amaran sinceramente', 'Sus sentimientos podrán ser heridos y tendrá que dejar escapar algunos proyectos personales', 'Debe aprender a ser cálido, a preocuparse por el prójimo y a compartir pensamientos y vivencias espirituales con otras personas');
